### ISSUE TITLE
Problem in the readme file.

### ISSUE THREAD

**Issue by praksharma** [tianjuxue/jax-fem#14]
Can you please change this in the readme ([here](https://github.com/tianjuxue/jax-fem/blob/05dcd2f46cdbc700b0f45c27f15516e341b69a25/README.md?plain=1#L65))?
```sh
git clone git@github.com:tianjuxue/jax-fem.git
```
You can replace this with the HTTP cloning.
```sh
git clone https://github.com/tianjuxue/jax-fem.git
```

Otherwise people will get access denied.

**Comment by SNMS95** [comment]
Hi Prakash,

We will make a hotfix. Thanks for the find.
